object Versions {
    const val retrofit = "2.9.0"
    const val loggingInterceptor = "5.0.0-alpha.3"
    const val gson = "2.9.0"
    const val koin = "3.4.0"
    const val androidCore = "1.7.0"
    const val appCompat = "1.6.1"
    const val androidMaterial = "1.9.0"
    const val jUnit = "4.13.2"
    const val jUnitTest = "1.1.5"
    const val mockitoInline = "3.10.0"
    const val mockitoKotlin = "4.1.0"
    const val mockk = "1.13.3"
    const val espressoCore = "3.5.1"
    const val kotlinCompilerExtensionVersion = "1.4.3"
    const val runTimeKtx = "2.3.1"
    const val composeActivity = "1.3.1"
    const val composeUi = "1.4.3"
    const val composeMaterial = "1.2.0"
    const val composeRuntime = "2.6.0"
    const val composeLottie = "4.0.0"
    const val systemUiController = "0.27.0"
    const val coroutines = "1.4.2"
}
